%%{init: {'theme':'neutral'}}%%
flowchart LR
    p0((Channel.fromPath))
    p1([map])
    p2[bam2FastQ]
    p3((FastQ files))
    p4((Channel.fromPath))
    p5([map])
    p6([mix])
    subgraph megSAP[ ]
    direction TB
    p7[megSAPma]
    p8[megSAPvc]
    p9[megSAPcn]
    p10[megSAPsv]
    p11[megSAPdb]
    end
    p0 --> p1
    p1 -->|bam_channel| p2
    p2 --> p3
    p2 --> p6
    p4 --> p5
    p5 -->|fastq_channel| p6
    p6 --> megSAP
    p7 --> p8
    p8 --> p9
    p9 --> p10
    p10 --> p11
    p3 -.-> megSAP
